export const GET_COLLECTIONS_BEGIN = 'GET_COLLECTIONS_BEGIN'
export const GET_COLLECTIONS_CLEAR = 'GET_COLLECTIONS_CLEAR'
export const GET_COLLECTIONS_FAILURE = 'GET_COLLECTIONS_FAILURE'
export const GET_COLLECTIONS_SUCCESS = 'GET_COLLECTIONS_SUCCESS'
